import type { ChecklistCategory } from "./types";

export function getDefaultChecklists(): ChecklistCategory[] {
  return [
    {
      id: "shelter",
      name: "텐트 & 잠자리",
      emoji: "⛺",
      items: [
        { id: "tent", label: "텐트", checked: false },
        { id: "tent-poles", label: "텐트 폴대", checked: false },
        { id: "tent-stakes", label: "팩 & 해머", checked: false },
        { id: "ground-sheet", label: "그라운드시트", checked: false },
        { id: "sleeping-bag", label: "침낭", checked: false },
        { id: "sleeping-pad", label: "매트리스/에어매트", checked: false },
        { id: "pillow", label: "캠핑 베개", checked: false },
        { id: "canopy", label: "타프/차양막", checked: false },
      ],
    },
    {
      id: "kitchen",
      name: "취사도구",
      emoji: "🍳",
      items: [
        { id: "stove", label: "버너/스토브", checked: false },
        { id: "gas", label: "가스통", checked: false },
        { id: "pot", label: "코펠/냄비", checked: false },
        { id: "frying-pan", label: "프라이팬", checked: false },
        { id: "knife", label: "캠핑 칼", checked: false },
        { id: "cutting-board", label: "도마", checked: false },
        { id: "plates", label: "그릇/접시", checked: false },
        { id: "cups", label: "컵/텀블러", checked: false },
        { id: "utensils", label: "수저 & 젓가락", checked: false },
        { id: "can-opener", label: "캔따개", checked: false },
        { id: "cooler", label: "아이스박스/쿨러", checked: false },
        { id: "ice", label: "얼음", checked: false },
        { id: "dish-soap", label: "주방세제 & 수세미", checked: false },
        { id: "trash-bags", label: "쓰레기봉투", checked: false },
      ],
    },
    {
      id: "clothing",
      name: "의류 & 신발",
      emoji: "👕",
      items: [
        { id: "jacket", label: "방풍/방수 자켓", checked: false },
        { id: "fleece", label: "플리스/보온 레이어", checked: false },
        { id: "pants", label: "트레킹 바지", checked: false },
        { id: "tshirts", label: "티셔츠 (여분)", checked: false },
        { id: "underwear", label: "속옷 (여분)", checked: false },
        { id: "socks", label: "양말 (여분)", checked: false },
        { id: "hat", label: "모자/비니", checked: false },
        { id: "gloves", label: "장갑", checked: false },
        { id: "boots", label: "등산화/트레킹화", checked: false },
        { id: "sandals", label: "슬리퍼/샌들", checked: false },
        { id: "rain-gear", label: "우비/우산", checked: false },
      ],
    },
    {
      id: "hygiene",
      name: "위생 & 세면",
      emoji: "🧼",
      items: [
        { id: "toothbrush", label: "칫솔 & 치약", checked: false },
        { id: "shampoo", label: "샴푸/바디워시", checked: false },
        { id: "towel", label: "수건", checked: false },
        { id: "toilet-paper", label: "화장지", checked: false },
        { id: "wet-wipes", label: "물티슈", checked: false },
        { id: "sunscreen", label: "선크림", checked: false },
        { id: "insect-repellent", label: "모기약/방충제", checked: false },
        { id: "hand-sanitizer", label: "손 소독제", checked: false },
      ],
    },
    {
      id: "safety",
      name: "안전 & 응급",
      emoji: "🩹",
      items: [
        { id: "first-aid", label: "구급함", checked: false },
        { id: "headlamp", label: "헤드랜턴 & 건전지", checked: false },
        { id: "lighter", label: "라이터/성냥", checked: false },
        { id: "whistle", label: "호루라기", checked: false },
        { id: "map", label: "지도/GPS", checked: false },
        { id: "emergency-contact", label: "비상연락처 메모", checked: false },
      ],
    },
    {
      id: "extras",
      name: "편의 & 기타",
      emoji: "🎒",
      items: [
        { id: "chair", label: "캠핑 의자", checked: false },
        { id: "table", label: "캠핑 테이블", checked: false },
        { id: "lantern", label: "랜턴/조명", checked: false },
        { id: "firewood", label: "장작/숯", checked: false },
        { id: "power-bank", label: "보조 배터리", checked: false },
        { id: "charger", label: "충전기/케이블", checked: false },
        { id: "camera", label: "카메라", checked: false },
        { id: "book", label: "책/보드게임", checked: false },
      ],
    },
  ];
}
