import type { PlaceItem } from "./types";

export type CuratedPlace = Omit<PlaceItem, "id" | "whyPicked"> & { tags: string[] };

export const CURATED_PLACES: CuratedPlace[] = [
  // ── Food ──────────────────────────────────────────────────────────────────────
  {
    name: "Gwangjang Market",
    emoji: "🥟",
    category: "food",
    neighborhood: "Jongno",
    duration: "2 hours",
    bestTime: "Weekday morning 9–11am or evening after 6pm",
    expertTip: "Go to Stall 92 (빈대떡 골목) for the crispiest bindaetteok — order extra with막걸리 for ₩8,000 total",
    insiderNote: "The gimbap grandmas in the back alley serve fresher rolls than the famous front stalls — half the queue, same quality",
    tags: ["street food", "market", "local", "budget"],
  },
  {
    name: "Tosokchon Samgyetang",
    emoji: "🍲",
    category: "food",
    neighborhood: "Jongno",
    duration: "1.5 hours",
    bestTime: "Weekday lunch 11am–12pm (before the line forms)",
    expertTip: "Order the regular ginseng chicken — the premium version isn't noticeably better. Ask for extra rice on the side",
    insiderNote: "The side door on the left has a shorter wait than the main entrance. Show up 10 min before opening",
    tags: ["traditional", "korean", "soup", "mid-range"],
  },
  {
    name: "Noryangjin Fish Market",
    emoji: "🦑",
    category: "food",
    neighborhood: "Yeouido",
    duration: "2 hours",
    bestTime: "Early morning 6–8am for the freshest catch; evening for sashimi dinner",
    expertTip: "Buy live octopus from Hall B, then take it to the 2nd floor restaurants — they'll prepare it for a ₩5,000 cooking fee",
    insiderNote: "The auction floor runs at 3am — sneak in quietly and you'll see the real wholesale market before tourists arrive",
    tags: ["seafood", "market", "local", "experience"],
  },
  {
    name: "Myeongdong Kyoja",
    emoji: "🍜",
    category: "food",
    neighborhood: "Myeongdong",
    duration: "45 minutes",
    bestTime: "11:30am sharp when they open — queue fills up fast",
    expertTip: "Order kalguksu (knife-cut noodle soup) + mandu combo for ₩13,000. The broth is made fresh every morning",
    insiderNote: "The branch on the 2nd floor has shorter queues than street level — most tourists don't know it exists",
    tags: ["noodles", "dumplings", "budget", "local"],
  },
  {
    name: "Tongin Market Dosirak Café",
    emoji: "🍱",
    category: "food",
    neighborhood: "Jongno",
    duration: "1.5 hours",
    bestTime: "Lunch only (11am–2pm) — closes once tokens run out",
    expertTip: "Buy coin tokens at the entrance, then fill your wooden box with any side dishes you like from each vendor — budget ₩5,000",
    insiderNote: "This market still uses Japanese colonial-era coin system. Each vendor is a different family recipe — mix and match freely",
    tags: ["local", "budget", "lunch", "unique experience"],
  },
  {
    name: "Maple Tree House",
    emoji: "🥩",
    category: "food",
    neighborhood: "Itaewon",
    duration: "2 hours",
    bestTime: "Dinner reservation required — book 2 weeks ahead for weekends",
    expertTip: "The oak-smoked galbi short rib is the signature — skip the wagyu and go local Korean black cattle (hanwoo)",
    insiderNote: "The private room on the 3rd floor has a fireplace. Request it when booking — most guests don't know to ask",
    tags: ["BBQ", "luxury", "special occasion", "meat"],
  },
  {
    name: "Hanilkwan",
    emoji: "🍚",
    category: "food",
    neighborhood: "Insadong",
    duration: "1.5 hours",
    bestTime: "Weekday lunch 12–1pm",
    expertTip: "Order the kongbap (bean rice) set — it comes with 12 traditional side dishes that change daily",
    insiderNote: "One of the last places serving true hanjeongsik (royal court cuisine) at non-tourist prices. In business since 1942",
    tags: ["traditional", "royal cuisine", "mid-range", "authentic"],
  },
  {
    name: "Palsaik Samgyeopsal",
    emoji: "🐷",
    category: "food",
    neighborhood: "Hongdae",
    duration: "2 hours",
    bestTime: "Dinner 6–8pm, arrive before 7pm to avoid full queue",
    expertTip: "Try all 8 marinades — the red wine and doenjang (fermented soybean) are the standouts. Wrap in sesame leaves, not just lettuce",
    insiderNote: "The pork here is sourced from Jeju black pig — it's leaner with a cleaner taste than regular pork belly",
    tags: ["BBQ", "pork belly", "mid-range", "fun"],
  },
  {
    name: "Mangwon Market",
    emoji: "🥪",
    category: "food",
    neighborhood: "Mangwon",
    duration: "1.5 hours",
    bestTime: "Weekend morning 9am–12pm",
    expertTip: "The tteok (rice cake) stall at the east entrance makes flavors only available on weekends. Arrive early — sells out by noon",
    insiderNote: "This is where Mapo locals actually shop. Far less touristy than Gwangjang — prices are 30% cheaper for the same quality",
    tags: ["market", "local", "budget", "neighborhood"],
  },
  {
    name: "Buam-dong Cafe Street",
    emoji: "🫖",
    category: "food",
    neighborhood: "Bukchon",
    duration: "2 hours",
    bestTime: "Weekday afternoon 2–4pm for mountain views and calm",
    expertTip: "Café Bora in Insadong gets tourist lines — come here instead for the same purple taro latte without the wait",
    insiderNote: "This sleepy neighbourhood above Gyeongbokgung is where Seoul artists and filmmakers live — walls are full of street art",
    tags: ["cafe", "scenic", "quiet", "local"],
  },

  // ── Attractions ───────────────────────────────────────────────────────────────
  {
    name: "Gyeongbokgung Palace",
    emoji: "🏯",
    category: "attraction",
    neighborhood: "Gyeongbokgung",
    duration: "2.5 hours",
    bestTime: "Weekday 9–10am; Changing of the Guard ceremony at 10am and 2pm",
    expertTip: "Rent hanbok at the gate (₩15,000/hour) — hanbok wearers enter free and make incredible photos near the main gate",
    insiderNote: "The National Folk Museum inside is free separately — most visitors walk past it. The afternoon light behind Geunjeongjeon hits perfectly at 4pm",
    tags: ["palace", "history", "culture", "photo"],
  },
  {
    name: "Changdeokgung & Secret Garden",
    emoji: "🌳",
    category: "attraction",
    neighborhood: "Jongno",
    duration: "2 hours",
    bestTime: "Morning 9am tour — only 50 people per session",
    expertTip: "Book the English Secret Garden tour online a week ahead — it's limited to 50 visitors and sells out fast",
    insiderNote: "Unlike Gyeongbokgung, Changdeokgung was the royal family's actual residence for 300 years. The architecture is more intimate and authentic",
    tags: ["palace", "garden", "history", "guided tour"],
  },
  {
    name: "Bukchon Hanok Village",
    emoji: "🏘️",
    category: "attraction",
    neighborhood: "Bukchon",
    duration: "2 hours",
    bestTime: "Weekday 8–9am before tour groups; golden light for photos",
    expertTip: "Take alley 11 from the main viewpoint — it leads to a hidden courtyard café that most tourists completely miss",
    insiderNote: "Many hanok buildings are still private homes — keep noise to a minimum after 9am. Residents have posted signs in multiple languages",
    tags: ["hanok", "traditional", "photo", "culture"],
  },
  {
    name: "Namsan Seoul Tower",
    emoji: "🗼",
    category: "attraction",
    neighborhood: "Namsan",
    duration: "2 hours",
    bestTime: "Sunset 1 hour before dusk for views; night for city lights",
    expertTip: "Skip the cable car and hike the 40-min Bugak trail — quieter, free, and the view from halfway up is actually better",
    insiderNote: "The observation deck closes early on cloudy days — call ahead. The love lock area below the tower is free with great skyline views",
    tags: ["views", "sunset", "romantic", "iconic"],
  },
  {
    name: "Cheonggyecheon Stream",
    emoji: "🌊",
    category: "attraction",
    neighborhood: "Euljiro",
    duration: "1.5 hours",
    bestTime: "Evening after 7pm when it's lit up and cooler",
    expertTip: "Start at Cheonggye Square and walk east toward Gwangjang — the stream gets quieter and more scenic the further you go",
    insiderNote: "This urban stream was buried under concrete highways until 2005. Beneath your feet is an ancient natural waterway — it's an engineering miracle",
    tags: ["walking", "urban", "scenic", "evening"],
  },
  {
    name: "War Memorial of Korea",
    emoji: "🎖️",
    category: "attraction",
    neighborhood: "Yongsan",
    duration: "2.5 hours",
    bestTime: "Weekday morning — quieter and better for reflection",
    expertTip: "The outdoor exhibition has actual fighter jets, tanks and helicopters you can get up close to — free and photo-worthy",
    insiderNote: "This is one of Seoul's best-kept cultural secrets among foreign visitors. The memorial hall on the 3rd floor about the Korean War is deeply moving",
    tags: ["history", "museum", "free", "culture"],
  },
  {
    name: "Lotte World Tower Sky Walk",
    emoji: "🏙️",
    category: "attraction",
    neighborhood: "Jamsil",
    duration: "1.5 hours",
    bestTime: "Clear day 2–4pm; or evening for city lights",
    expertTip: "Buy the Seoul Sky combo online for 15% discount. Go on a weekday — weekends are packed with families",
    insiderNote: "The glass floor walkway at 478m is on the exterior — people either love or hate it. The views of Han River from here are Seoul's best",
    tags: ["views", "skyscraper", "modern", "luxury"],
  },
  {
    name: "Han River Cycling",
    emoji: "🚴",
    category: "attraction",
    neighborhood: "Yeouido",
    duration: "3 hours",
    bestTime: "Weekend morning 7–10am before heat; rent bikes at Yeouinaru station",
    expertTip: "Rent a tandem bike at Yeouinaru for ₩6,000/hour — cycle east to Mangwon Park for the best Han River picnic spot",
    insiderNote: "Convenience stores along the river sell fried chicken (not just snacks) — locals do entire chicken dinners on the riverside grass",
    tags: ["cycling", "outdoor", "scenic", "active"],
  },
  {
    name: "Ihwa Mural Village",
    emoji: "🎨",
    category: "attraction",
    neighborhood: "Jongno",
    duration: "1.5 hours",
    bestTime: "Late afternoon for cooler temp and best lighting on murals",
    expertTip: "The famous cat mural is at the top of the slope — follow the hand-painted arrows. Continues into Naksan Park for city views",
    insiderNote: "This hillside village was almost demolished for redevelopment in 2006. Artists moved in and painted the walls to save it — it worked",
    tags: ["art", "walking", "neighbourhood", "photo"],
  },
  {
    name: "Seonyudo Park",
    emoji: "🌿",
    category: "attraction",
    neighborhood: "Yeouido",
    duration: "2 hours",
    bestTime: "Weekend morning for fewer people; spring for water views",
    expertTip: "The old water purification plant columns create unique Instagram-worthy photos — go at golden hour for the best light",
    insiderNote: "This was Seoul's water treatment plant until 2000, then repurposed as an ecological park. The industrial architecture contrasts beautifully with the plants",
    tags: ["park", "design", "nature", "photo"],
  },

  // ── Shopping ──────────────────────────────────────────────────────────────────
  {
    name: "Myeongdong Shopping Street",
    emoji: "🛍️",
    category: "shopping",
    neighborhood: "Myeongdong",
    duration: "2.5 hours",
    bestTime: "Weekday afternoon 2–5pm before evening crowds",
    expertTip: "The skincare deals are on the side streets parallel to the main road — 30% cheaper than the same products on the main strip",
    insiderNote: "Vendors accept Chinese yuan, Japanese yen and sometimes USD — no need to exchange first for street food. Never pay first price for street snacks",
    tags: ["cosmetics", "street food", "shopping", "budget"],
  },
  {
    name: "COEX Mall & Starfield Library",
    emoji: "📚",
    category: "shopping",
    neighborhood: "Gangnam",
    duration: "2 hours",
    bestTime: "Weekday for fewer people at the library; weekends get crowded",
    expertTip: "The Starfield Library photo is best from the 2nd floor mezzanine — get there 30 mins before it opens to beat the queue",
    insiderNote: "COEX has a basement aquarium that's surprisingly good for kids — far cheaper than Lotte World Aquarium with shorter lines",
    tags: ["mall", "library", "photo", "modern"],
  },
  {
    name: "Dongdaemun Design Plaza (DDP)",
    emoji: "🌐",
    category: "shopping",
    neighborhood: "Dongdaemun",
    duration: "2 hours",
    bestTime: "Evening — lit up beautifully after dark, markets open 10pm",
    expertTip: "The DDP design market opens at 10:30pm. Korean fashion wholesalers sell to the public here at near-wholesale prices after midnight",
    insiderNote: "DDP sits on Seoul's 600-year-old city wall ruins. Walk the elevated walkway to see excavated ruins beneath the building",
    tags: ["architecture", "night market", "fashion", "design"],
  },
  {
    name: "Namdaemun Market",
    emoji: "🧶",
    category: "shopping",
    neighborhood: "Namdaemun",
    duration: "2 hours",
    bestTime: "Early morning 6–9am when wholesale buyers shop",
    expertTip: "Korean ginseng products are authentically priced here vs tourist shops — go to stalls with '6-year' red ginseng certificate signs",
    insiderNote: "Many stalls open from 11pm for overnight wholesale — coming at 2am gives you a completely different market experience",
    tags: ["market", "bargaining", "wholesale", "local"],
  },
  {
    name: "Hongdae Shopping & Street Performers",
    emoji: "🎭",
    category: "shopping",
    neighborhood: "Hongdae",
    duration: "2.5 hours",
    bestTime: "Friday/Saturday evening 7–10pm for street performers",
    expertTip: "The underground shopping mall below Hongdae station has Korean indie fashion brands 40% cheaper than above-ground shops",
    insiderNote: "The playground near Sangsangmadang hosts the best street performers on weekends — free live music from 7pm",
    tags: ["fashion", "nightlife", "young", "entertainment"],
  },
  {
    name: "Insadong Antique & Craft Street",
    emoji: "🏺",
    category: "shopping",
    neighborhood: "Insadong",
    duration: "2 hours",
    bestTime: "Sunday when the road becomes pedestrian-only",
    expertTip: "The second floor of Ssamziegil courtyard has the best local ceramics and handmade jewelry — prices are fixed and fair",
    insiderNote: "The Starbucks sign here is the only one in the world written in Korean — the city required it to preserve the traditional character of the street",
    tags: ["antiques", "crafts", "souvenirs", "culture"],
  },
  {
    name: "Common Ground Container Mall",
    emoji: "📦",
    category: "shopping",
    neighborhood: "Hongdae",
    duration: "1.5 hours",
    bestTime: "Weekend afternoon — food trucks and pop-up events",
    expertTip: "The rooftop terrace has the best view of the Konkuk University area — and food trucks serve excellent Korean-fusion snacks",
    insiderNote: "Built entirely from upcycled shipping containers in 2015. The indie brands inside rotate seasonally — always something new",
    tags: ["indie brands", "food trucks", "young", "unique"],
  },

  // ── Cafés ─────────────────────────────────────────────────────────────────────
  {
    name: "Anthracite Coffee Hapjeong",
    emoji: "☕",
    category: "cafe",
    neighborhood: "Hongdae",
    duration: "1 hour",
    bestTime: "Weekday morning 10am for quiet atmosphere",
    expertTip: "Order the hand-drip single origin — the barista will ask your flavour preference. The industrial space is best photographed from the mezzanine level",
    insiderNote: "This building was a shoe factory in the 1970s. The original machinery is still visible — it's a National Heritage-listed industrial space",
    tags: ["specialty coffee", "industrial", "photo", "aesthetic"],
  },
  {
    name: "Onion Anguk",
    emoji: "🥐",
    category: "cafe",
    neighborhood: "Bukchon",
    duration: "1 hour",
    bestTime: "Weekday morning 9–11am — bread sells out by noon",
    expertTip: "The sourdough and croissants sell out first — arrive early. Ask for the cardamom twist which isn't on the menu board",
    insiderNote: "Housed in a converted 1960s Korean-style building — the inner courtyard with original tilework is only visible from the back room",
    tags: ["bakery", "specialty coffee", "aesthetic", "Bukchon"],
  },
  {
    name: "Fritz Coffee Domamdong",
    emoji: "🎺",
    category: "cafe",
    neighborhood: "Mangwon",
    duration: "1 hour",
    bestTime: "Weekday morning — weekend lines stretch around the block",
    expertTip: "Fritz has a cult following for their bear-logo bags. Buy beans here — they're used in Seoul's best specialty coffee shops",
    insiderNote: "Fritz sources beans from farms they part-own in Ethiopia and Guatemala. The quality control is Korean-obsessive — every batch is cupped three times",
    tags: ["specialty coffee", "beans", "local cult", "Mapo"],
  },
  {
    name: "Seongsu Café District",
    emoji: "🏭",
    category: "cafe",
    neighborhood: "Seongsu-dong",
    duration: "2.5 hours",
    bestTime: "Weekday afternoon 1–4pm for the best light in the cafés",
    expertTip: "Wander the alleys between Ttukseom and Seongsu stations — each alley has 3–4 independent cafés. Don't follow the tourist map",
    insiderNote: "Seongsu is where Seoul's luxury fashion brands hold pop-ups. Check Instagram #성수동 the week you visit for current events",
    tags: ["cafe hopping", "industrial", "trendy", "Seongsu"],
  },
  {
    name: "Café Yeonnam-dong 239-20",
    emoji: "🖼️",
    category: "cafe",
    neighborhood: "Hongdae",
    duration: "1 hour",
    bestTime: "Afternoon 2–4pm for the best natural light",
    expertTip: "The entire interior is 2D trompe-l'oeil art — what looks like 3D furniture is painted on walls. Order a matcha for photos",
    insiderNote: "It's actually a pop-art installation by a Korean illustrator who got famous on Instagram. The concept changes every 2 years",
    tags: ["Instagram", "unique", "art cafe", "Hongdae"],
  },

  // ── Neighborhoods ──────────────────────────────────────────────────────────────
  {
    name: "Ikseon-dong Hanok Alley",
    emoji: "🏮",
    category: "neighborhood",
    neighborhood: "Jongno",
    duration: "2 hours",
    bestTime: "Evening 6–9pm when the hanok bars and lanterns are lit",
    expertTip: "The narrow alley behind the main street (Ikseon-ro) has quieter, cheaper bars and restaurants — start there before the main strip",
    insiderNote: "These 1930s hanok were slated for demolition in 2014. A preservation campaign by local residents saved the entire block — it's now one of Seoul's most Instagrammed areas",
    tags: ["hanok", "bars", "evening", "trendy"],
  },
  {
    name: "Haebangchon (HBC)",
    emoji: "🌍",
    category: "neighborhood",
    neighborhood: "Itaewon",
    duration: "2 hours",
    bestTime: "Evening for the international bar/restaurant scene",
    expertTip: "HBC has the best non-Korean food in Seoul — Middle Eastern, Mexican, Italian from immigrant-owned restaurants. No tourist markup",
    insiderNote: "Originally a US military camp follower settlement, now home to Seoul's most international community. It's where expats actually live and eat",
    tags: ["international", "bars", "diverse", "local"],
  },
  {
    name: "Garosu-gil (Sinsa-dong)",
    emoji: "🌲",
    category: "neighborhood",
    neighborhood: "Sinsa",
    duration: "2 hours",
    bestTime: "Weekday afternoon for calm browsing; autumn for ginkgo trees",
    expertTip: "The boutiques off the main ginkgo tree boulevard have Korean designer clothes at lower prices than Cheongdam flagship stores",
    insiderNote: "Garosu means 'tree-lined' — in autumn the ginkgo trees turn gold simultaneously, creating a tunnel of yellow. Peak usually mid-to-late November",
    tags: ["boutique shopping", "trees", "design", "Gangnam"],
  },
  {
    name: "Samcheong-dong Street",
    emoji: "🎪",
    category: "neighborhood",
    neighborhood: "Samcheong-dong",
    duration: "2 hours",
    bestTime: "Weekday morning for quiet gallery hopping",
    expertTip: "The National Museum of Contemporary Art (free) is at the top of the street — do galleries on the way down, end with a meal at the bottom",
    insiderNote: "Samcheong means 'three clears': clear water, clear mountains, clear hearts. The galleries here show genuine emerging Korean artists — prices are accessible",
    tags: ["galleries", "art", "quiet", "culture"],
  },
  {
    name: "Mangwon-dong Neighbourhood",
    emoji: "🏠",
    category: "neighborhood",
    neighborhood: "Mangwon",
    duration: "2 hours",
    bestTime: "Saturday morning for the weekend market feel",
    expertTip: "Mangwon Market's weekend street food stalls on Saturday morning are a local institution — bindaetteok, fishcake and hand-made rice cakes",
    insiderNote: "This is the most authentically residential area in the guide — no major tourist sites, just real Seoul life. Locals are friendly to curious visitors",
    tags: ["local", "residential", "market", "authentic"],
  },
];
