export type PlaceCategory = "accommodation" | "restaurants" | "shopping" | "experiences" | "cafes";

export interface Place {
  id: string;
  name: string;
  category: PlaceCategory;
  description: string;
  location: string;
  neighborhood: string;
  priceRange: "$" | "$$" | "$$$" | "$$$$";
  rating: number;
  lat: number;
  lng: number;
  tags: string[];
}

export const CATEGORIES: { id: PlaceCategory; label: string; emoji: string }[] = [
  { id: "accommodation", label: "Accommodation", emoji: "🏨" },
  { id: "restaurants", label: "Restaurants", emoji: "🍽️" },
  { id: "shopping", label: "Shopping", emoji: "🛍️" },
  { id: "experiences", label: "Experiences", emoji: "🎭" },
  { id: "cafes", label: "Cafes", emoji: "☕" },
];

export const PLACES: Place[] = [
  // Accommodation
  {
    id: "acc-1",
    name: "Lotte Hotel Seoul",
    category: "accommodation",
    description: "Iconic 5-star hotel in the heart of Myeongdong with stunning city views.",
    location: "Myeongdong",
    neighborhood: "Jung-gu",
    priceRange: "$$$$",
    rating: 4.7,
    lat: 37.5641,
    lng: 126.9822,
    tags: ["Luxury", "City view", "Business"],
  },
  {
    id: "acc-2",
    name: "Bukchon Hanok Guesthouse",
    category: "accommodation",
    description: "Stay in a traditional Korean wooden house in the historic Bukchon village.",
    location: "Bukchon",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5826,
    lng: 126.9836,
    tags: ["Traditional", "Cultural", "Romantic"],
  },
  {
    id: "acc-3",
    name: "Generator Seoul Hongdae",
    category: "accommodation",
    description: "Trendy hostel-hotel hybrid near Hongdae with vibrant nightlife scene.",
    location: "Hongdae",
    neighborhood: "Mapo-gu",
    priceRange: "$",
    rating: 4.3,
    lat: 37.5563,
    lng: 126.9238,
    tags: ["Budget", "Social", "Nightlife"],
  },
  {
    id: "acc-4",
    name: "Park Hyatt Seoul",
    category: "accommodation",
    description: "Ultra-modern luxury hotel in Gangnam with panoramic views and infinity pool.",
    location: "Gangnam",
    neighborhood: "Gangnam-gu",
    priceRange: "$$$$",
    rating: 4.8,
    lat: 37.5087,
    lng: 127.0602,
    tags: ["Luxury", "Pool", "Business"],
  },
  {
    id: "acc-5",
    name: "Itaewon 1957 Hotel",
    category: "accommodation",
    description: "Boutique hotel in Itaewon with a cosmopolitan feel and great dining.",
    location: "Itaewon",
    neighborhood: "Yongsan-gu",
    priceRange: "$$$",
    rating: 4.4,
    lat: 37.5344,
    lng: 126.9947,
    tags: ["Boutique", "International", "Dining"],
  },
  {
    id: "acc-6",
    name: "Jongno Guesthouse",
    category: "accommodation",
    description: "Cozy guesthouse near Gyeongbokgung Palace, ideal for solo travelers.",
    location: "Jongno",
    neighborhood: "Jongno-gu",
    priceRange: "$",
    rating: 4.2,
    lat: 37.5757,
    lng: 126.9769,
    tags: ["Budget", "Solo", "Culture"],
  },

  // Restaurants
  {
    id: "rest-1",
    name: "Gwangjang Market",
    category: "restaurants",
    description: "Seoul's oldest market — famous for bindaetteok, mayak gimbap, and live octopus.",
    location: "Jongno",
    neighborhood: "Jongno-gu",
    priceRange: "$",
    rating: 4.6,
    lat: 37.5699,
    lng: 126.9994,
    tags: ["Street food", "Traditional", "Market"],
  },
  {
    id: "rest-2",
    name: "Tosokchon Samgyetang",
    category: "restaurants",
    description: "Legendary ginseng chicken soup restaurant near Gyeongbokgung, open since 1983.",
    location: "Cheong Wa Dae",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5826,
    lng: 126.9686,
    tags: ["Korean", "Traditional", "Health food"],
  },
  {
    id: "rest-3",
    name: "Maple Tree House Itaewon",
    category: "restaurants",
    description: "Premium Korean BBQ with top-grade hanwoo beef in a stylish setting.",
    location: "Itaewon",
    neighborhood: "Yongsan-gu",
    priceRange: "$$$",
    rating: 4.7,
    lat: 37.5352,
    lng: 126.9942,
    tags: ["BBQ", "Premium", "Date night"],
  },
  {
    id: "rest-4",
    name: "Noryangjin Fish Market",
    category: "restaurants",
    description: "24-hour seafood market — buy fresh fish downstairs, take it upstairs to cook.",
    location: "Noryangjin",
    neighborhood: "Dongjak-gu",
    priceRange: "$$",
    rating: 4.4,
    lat: 37.5128,
    lng: 126.9427,
    tags: ["Seafood", "Market", "Experience"],
  },
  {
    id: "rest-5",
    name: "Myeongdong Kyoja",
    category: "restaurants",
    description: "Famous for handmade kalguksu (knife noodles) and mandu. Expect queues.",
    location: "Myeongdong",
    neighborhood: "Jung-gu",
    priceRange: "$",
    rating: 4.5,
    lat: 37.5637,
    lng: 126.9847,
    tags: ["Noodles", "Local", "Queue"],
  },
  {
    id: "rest-6",
    name: "Jungsik",
    category: "restaurants",
    description: "Michelin 2-star modern Korean cuisine — tasting menus that redefine Korean food.",
    location: "Gangnam",
    neighborhood: "Gangnam-gu",
    priceRange: "$$$$",
    rating: 4.9,
    lat: 37.5223,
    lng: 127.0256,
    tags: ["Fine dining", "Michelin", "Tasting menu"],
  },

  // Shopping
  {
    id: "shop-1",
    name: "Myeongdong Shopping Street",
    category: "shopping",
    description: "Korea's #1 shopping destination — K-beauty, fashion, and street food all in one.",
    location: "Myeongdong",
    neighborhood: "Jung-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5636,
    lng: 126.9834,
    tags: ["K-beauty", "Fashion", "Street food"],
  },
  {
    id: "shop-2",
    name: "Dongdaemun Design Plaza",
    category: "shopping",
    description: "Futuristic 24-hour fashion complex designed by Zaha Hadid.",
    location: "Dongdaemun",
    neighborhood: "Jung-gu",
    priceRange: "$$",
    rating: 4.6,
    lat: 37.5673,
    lng: 127.0094,
    tags: ["Fashion", "Design", "24-hour"],
  },
  {
    id: "shop-3",
    name: "Insadong Ssamziegil",
    category: "shopping",
    description: "Quirky open-air mall with indie brands, crafts, and Korean art.",
    location: "Insadong",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.4,
    lat: 37.5742,
    lng: 126.9857,
    tags: ["Indie", "Crafts", "Art"],
  },
  {
    id: "shop-4",
    name: "COEX Mall",
    category: "shopping",
    description: "Massive underground mall in Gangnam with aquarium, library, and everything else.",
    location: "Gangnam",
    neighborhood: "Gangnam-gu",
    priceRange: "$$",
    rating: 4.4,
    lat: 37.5126,
    lng: 127.0596,
    tags: ["Mall", "Underground", "Family"],
  },
  {
    id: "shop-5",
    name: "Namdaemun Market",
    category: "shopping",
    description: "Korea's largest traditional market — clothing, accessories, food, and more.",
    location: "Namdaemun",
    neighborhood: "Jung-gu",
    priceRange: "$",
    rating: 4.3,
    lat: 37.5589,
    lng: 126.9766,
    tags: ["Traditional", "Wholesale", "Bargain"],
  },
  {
    id: "shop-6",
    name: "Hongdae Free Market",
    category: "shopping",
    description: "Weekend flea market run by local artists — unique handmade goods.",
    location: "Hongdae",
    neighborhood: "Mapo-gu",
    priceRange: "$",
    rating: 4.5,
    lat: 37.5557,
    lng: 126.9245,
    tags: ["Art", "Handmade", "Weekend"],
  },

  // Experiences
  {
    id: "exp-1",
    name: "Gyeongbokgung Palace",
    category: "experiences",
    description: "Joseon dynasty's main palace — wear a hanbok for free entry.",
    location: "Gwanghwamun",
    neighborhood: "Jongno-gu",
    priceRange: "$",
    rating: 4.7,
    lat: 37.5796,
    lng: 126.9770,
    tags: ["History", "Hanbok", "Photography"],
  },
  {
    id: "exp-2",
    name: "N Seoul Tower",
    category: "experiences",
    description: "Iconic tower atop Namsan Mountain with 360° views over Seoul.",
    location: "Namsan",
    neighborhood: "Yongsan-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5512,
    lng: 126.9882,
    tags: ["Views", "Romantic", "Landmark"],
  },
  {
    id: "exp-3",
    name: "Han River Cycling",
    category: "experiences",
    description: "Rent a bike and cycle along the Han River — great for sunsets.",
    location: "Han River",
    neighborhood: "Yeongdeungpo-gu",
    priceRange: "$",
    rating: 4.6,
    lat: 37.5219,
    lng: 126.9368,
    tags: ["Outdoors", "Active", "Sunset"],
  },
  {
    id: "exp-4",
    name: "K-Drama Tour",
    category: "experiences",
    description: "Visit famous filming locations from popular K-dramas around Seoul.",
    location: "Various",
    neighborhood: "Seoul",
    priceRange: "$$",
    rating: 4.7,
    lat: 37.5665,
    lng: 126.9780,
    tags: ["K-drama", "Tour", "Fan experience"],
  },
  {
    id: "exp-5",
    name: "Korean Cooking Class",
    category: "experiences",
    description: "Learn to make kimchi, bibimbap, and tteokbokki with a local chef.",
    location: "Insadong",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.8,
    lat: 37.5742,
    lng: 126.9848,
    tags: ["Cooking", "Cultural", "Hands-on"],
  },
  {
    id: "exp-6",
    name: "Bukchon Hanok Village Walk",
    category: "experiences",
    description: "Stroll through preserved hanok alleys with stunning cityscape views.",
    location: "Bukchon",
    neighborhood: "Jongno-gu",
    priceRange: "$",
    rating: 4.5,
    lat: 37.5826,
    lng: 126.9836,
    tags: ["Walking", "Architecture", "Free"],
  },

  // Cafes
  {
    id: "cafe-1",
    name: "Cafe Bora",
    category: "cafes",
    description: "Iconic purple taro soft-serve in a beautiful hanok — always a queue.",
    location: "Insadong",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5749,
    lng: 126.9855,
    tags: ["Instagrammable", "Dessert", "Hanok"],
  },
  {
    id: "cafe-2",
    name: "Fritz Coffee Company",
    category: "cafes",
    description: "Seoul's best specialty coffee, beloved by baristas worldwide.",
    location: "Mapo",
    neighborhood: "Mapo-gu",
    priceRange: "$$",
    rating: 4.7,
    lat: 37.5489,
    lng: 126.9108,
    tags: ["Specialty coffee", "Bakery", "Hipster"],
  },
  {
    id: "cafe-3",
    name: "Sky Terrace Cafe Namsan",
    category: "cafes",
    description: "Rooftop cafe with unobstructed views of Namsan Tower.",
    location: "Namsan",
    neighborhood: "Yongsan-gu",
    priceRange: "$$$",
    rating: 4.4,
    lat: 37.5505,
    lng: 126.9887,
    tags: ["Views", "Rooftop", "Date spot"],
  },
  {
    id: "cafe-4",
    name: "Onion Anguk",
    category: "cafes",
    description: "Stunning cafe in a renovated military warehouse near Bukchon.",
    location: "Anguk",
    neighborhood: "Jongno-gu",
    priceRange: "$$",
    rating: 4.8,
    lat: 37.5811,
    lng: 126.9813,
    tags: ["Architecture", "Bakery", "Aesthetic"],
  },
  {
    id: "cafe-5",
    name: "Cafe Layered",
    category: "cafes",
    description: "Pastel aesthetic multi-floor cafe famous for matcha and desserts.",
    location: "Mapo",
    neighborhood: "Mapo-gu",
    priceRange: "$$",
    rating: 4.5,
    lat: 37.5494,
    lng: 126.9124,
    tags: ["Matcha", "Dessert", "Aesthetic"],
  },
  {
    id: "cafe-6",
    name: "Coffee Libre",
    category: "cafes",
    description: "Pioneer of Seoul's third-wave coffee movement. Simple, exceptional.",
    location: "Hongdae",
    neighborhood: "Mapo-gu",
    priceRange: "$",
    rating: 4.6,
    lat: 37.5564,
    lng: 126.9233,
    tags: ["Specialty coffee", "Minimalist", "Local"],
  },
];

export function getPlacesByCategory(category: PlaceCategory): Place[] {
  return PLACES.filter((p) => p.category === category);
}
